---
title: "recreating_nytimes_viz"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{recreating_nytimes_viz}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggtriangles)
library(urbnmapr)


# download county and state maps
counties <- get_urbn_map('counties', sf=T)
states <- get_urbn_map('states', sf=T)


# assign random values
counties$values <- ((rbinom(n = nrow(counties), prob = 0.6, size = 1)-0.5)*2) * rlnorm(n = nrow(counties))


# now using geom_triangle ############################################

ggplot() +
  geom_sf(data = counties,
          mapping = aes(
          fill = factor(values > 0),
          size = factor(values > 0),
          color = factor(values > 0)
          )) +
  geom_sf(data = states, aes(), size = 0.5, color = 'black', fill = NA) +
  geom_triangles(
    data =
      bind_cols(
        counties %>% filter(values > 0),
        counties %>% filter(values > 0) %>%
          sf::st_centroid() %>%
          sf::st_coordinates(.) %>%
          as.data.frame()),
    mapping = aes(x = X, y = Y, z = values),
    width = 1, height_scale = .15,
    fill = '#c0392b', color = '#c0392b', alpha = 0.8) +
  scale_fill_manual(values = c(`TRUE` = 'lightpink', `FALSE` = 'white')) +
  scale_size_manual(values = c(`TRUE` = .05, `FALSE` = 0)) +
  scale_color_manual(values = c(`TRUE` = "#c0392b", `FALSE` = 'white')) +
  theme_void() + 
  theme(legend.position = 'none')


darkgreen <- colorspace::lighten('#4e7c71')
lightgreen <- colorspace::lighten("#bacac9", amount = 0.5)

ggplot() +
  geom_sf(data = counties,
          mapping = aes(
          fill = factor(values < 0),
          size = factor(values < 0),
          color = factor(values < 0)
          )) +
  geom_sf(data = states, aes(), size = 0.5, color = 'black', fill = NA) +
  geom_triangles(
    data =
      bind_cols(
        counties %>% filter(values < 0),
        counties %>% filter(values < 0) %>%
          sf::st_centroid() %>%
          sf::st_coordinates(.) %>%
          as.data.frame()),
    mapping = aes(x = X, y = Y, z = values),
    width = 7, height_scale = .7,
    fill = darkgreen, color = darkgreen, alpha = 0.8) +
  scale_fill_manual(values = c(`TRUE` = lightgreen, `FALSE` = 'white')) +
  scale_size_manual(values = c(`TRUE` = .05, `FALSE` = 0)) +
  scale_color_manual(values = c(`TRUE` = darkgreen, `FALSE` = 'white')) +
  theme_void() + 
  theme(legend.position = 'none')


```


Now do it with NYT data

```{r}
nyt2020 <- readr::read_csv("https://github.com/nytimes/covid-19-data/raw/master/rolling-averages/us-counties-2020.csv")
nyt2021 <- readr::read_csv("https://github.com/nytimes/covid-19-data/raw/master/rolling-averages/us-counties-2021.csv") 

nyt2020avg <- nyt2020 %>% group_by(geoid, county, state) %>% 
  filter(date > lubridate::ymd("2020-03-01")) %>% 
  summarize(avg_death_rate = mean(deaths_avg_per_100k, na.rm=T))

nyt2021avg <- nyt2021 %>% group_by(geoid, county, state) %>% 
  summarize(avg_death_rate = mean(deaths_avg_per_100k, na.rm=T))


library(magrittr)
nyt2020avg %<>% rename(avg2020 = avg_death_rate)
nyt2021avg %<>% rename(avg2021 = avg_death_rate)


avg_death_rates <- nyt2020avg %<>% left_join(nyt2021avg)

head(avg_death_rates)

avg_death_rates %<>% mutate(change = avg2021 - avg2020)

avg_death_rates %<>% mutate(fips = stringr::str_extract(geoid, "[0-9]+"))

counties <- urbnmapr::get_urbn_map('counties', sf = TRUE)

counties %<>% left_join(avg_death_rates %>% select(fips, change), by = c('county_fips' = 'fips'))


state_abbreviations <- 
tibble::tribble(
         ~state_name, ~state_abbv, ~state_abbv_med,
         "Alabama",                 "AL",                 "Ala.",
          "Alaska",                 "AK",               "Alaska",
         "Arizona",                 "AZ",                "Ariz.",
        "Arkansas",                 "AR",                 "Ark.",
      "California",                 "CA",               "Calif.",
        "Colorado",                 "CO",               "Color.",
     "Connecticut",                 "CT",                "Conn.",
        "Delaware",                 "DE",                 "Del.",
         "Florida",                 "FL",                 "Fla.",
         "Georgia",                 "GA",                  "Ga.",
          "Hawaii",                 "HI",               "Hawaii",
           "Idaho",                 "ID",                "Idaho",
        "Illinois",                 "IL",                 "Ill.",
         "Indiana",                 "IN",                 "Ind.",
            "Iowa",                 "IA",                 "Iowa",
          "Kansas",                 "KS",                 "Kan.",
        "Kentucky",                 "KY",                  "Ky.",
       "Louisiana",                 "LA",                  "La.",
           "Maine",                 "ME",                "Maine",
        "Maryland",                 "MD",                  "Md.",
   "Massachusetts",                 "MA",                "Mass.",
        "Michigan",                 "MI",                "Mich.",
       "Minnesota",                 "MN",                "Minn.",
     "Mississippi",                 "MS",                "Miss.",
        "Missouri",                 "MO",                  "Mo.",
         "Montana",                 "MT",                "Mont.",
        "Nebraska",                 "NE",                 "Neb.",
          "Nevada",                 "NV",                 "Nev.",
   "New Hampshire",                 "NH",                 "N.H.",
      "New Jersey",                 "NJ",                 "N.J.",
      "New Mexico",                 "NM",                 "N.M.",
        "New York",                 "NY",                 "N.Y.",
  "North Carolina",                 "NC",                 "N.C.",
    "North Dakota",                 "ND",                 "N.D.",
            "Ohio",                 "OH",                 "Ohio",
        "Oklahoma",                 "OK",                "Okla.",
          "Oregon",                 "OR",                 "Ore.",
    "Pennsylvania",                 "PA",                  "Pa.",
    "Rhode Island",                 "RI",                 "R.I.",
  "South Carolina",                 "SC",                 "S.C.",
    "South Dakota",                 "SD",               "S.Dak.",
       "Tennessee",                 "TN",                "Tenn.",
           "Texas",                 "TX",                 "Tex.",
            "Utah",                 "UT",                 "Utah",
         "Vermont",                 "VT",                 "V.T.",
        "Virginia",                 "VA",                  "Va.",
      "Washington",                 "WA",                "Wash.",
   "West Virginia",                 "WV",                "W.Va.",
       "Wisconsin",                 "WI",                 "Wis.",
         "Wyoming",                 "WY",                 "Wyo."
  )


state_centers <- sf::st_centroid(states)
state_centers_xy <- sf::st_coordinates(state_centers)
state_centers %<>% bind_cols(state_centers_xy %>% as.data.frame())
state_centers %<>% left_join(state_abbreviations)


lower_threshold <- 0.25

ggplot() +
  geom_sf(data = counties,
          mapping = aes(
          fill = factor(change > lower_threshold),
          size = factor(change > lower_threshold) %>% forcats::fct_explicit_na(na_level = "FALSE"),
          color = factor(change > lower_threshold)
          )) +
  geom_sf(data = states, aes(), size = 0.5, color = 'black', fill = NA) +
  geom_triangles(
    data =
      bind_cols(
        counties %>% filter(change > lower_threshold),
        counties %>% filter(change > lower_threshold) %>%
          sf::st_centroid() %>%
          sf::st_coordinates(.) %>%
          as.data.frame()),
    mapping = aes(x = X, y = Y, z = change),
    width = 5, height_scale = 5,
    fill = '#c0392b', color = '#c0392b') +
  geom_text(
    data = state_centers, 
    mapping = aes(x = X, y = Y, label = state_abbv_med),
    hjust = 0, vjust = 0
  ) + 
  scale_fill_manual(values = c(`TRUE` = 'lightpink', `FALSE` = 'white')) +
  scale_size_manual(values = c(`TRUE` = .05, `FALSE` = 0)) +
  scale_color_manual(values = c(`TRUE` = "#c0392b", `FALSE` = 'white')) +
  ggtitle("Counties where 2021 death rates were greater than 2020 death rates") + 
  theme_void() + 
  theme(legend.position = 'none', plot.title = element_text(hjust = 0.5, face = 'bold'))


library(here)
ggsave(here("img/nyt_increased_counties.png"), width = 14, height = 10)
ggsave(here("img/nyt_increased_counties.jpeg"), width = 14, height = 10)



upper_threshold = -0.1
ggplot() +
  geom_sf(data = counties,
          mapping = aes(
          fill = factor(change < upper_threshold),
          size = factor(change < upper_threshold) %>% forcats::fct_explicit_na(na_level = "FALSE"),
          color = factor(change < upper_threshold)
          )) +
  geom_sf(data = states, aes(), size = 0.5, color = 'black', fill = NA) +
  geom_triangles(
    data =
      bind_cols(
        counties %>% filter(change < upper_threshold),
        counties %>% filter(change < upper_threshold) %>%
          sf::st_centroid() %>%
          sf::st_coordinates(.) %>%
          as.data.frame()),
    mapping = aes(x = X, y = Y, z = change),
    width = 5, height_scale = 6,
    fill = darkgreen, color = darkgreen) +
  geom_text(
    data = state_centers, 
    mapping = aes(x = X, y = Y, label = state_abbv_med),
    hjust = 0, vjust = 0
  ) + 
  scale_fill_manual(values = c(`TRUE` = lightgreen, `FALSE` = 'white')) +
  scale_size_manual(values = c(`TRUE` = .05, `FALSE` = 0)) +
  scale_color_manual(values = c(`TRUE` = darkgreen, `FALSE` = 'white')) +
  ggtitle("Counties where 2021 death rates were less than 2020 death rates") + 
  theme_void() + 
  theme(legend.position = 'none', plot.title = element_text(hjust = 0.5, face = 'bold'))

ggsave(here("img/nyt_decreased_counties.png"), width = 14, height = 10)
ggsave(here("img/nyt_decreased_counties.jpeg"), width = 14, height = 10)



```
